### ISSUE TITLE
can't see volume level in detailed Sonos player view

### ISSUE THREAD

**Issue by kgiori** [tim-hellhake/sonos-adapter#22]
Not sure this is an add-on issue or a WebThings UI issue. But whether I zoom in/out in my browser, I can't see the volume level of the Sonos player because the "Group/Ungroup" label is always on top, and blocking it. Possible short-term workarounds:
* change label "Group/Ungroup" to "Un/group" so it doesn't wrap. (or remove that property for now? I'm not sure what it does...)
* change the order of the labels so that Volume is not next to "Group/Ungroup" (something that won't block its view)

Longer-term UI option:
* change labels to be transparent, rather than white on blue background (then could likely see the volume value even if overlapping with the label)
<img width="789" alt="Screen Shot 2020-12-06 at 9 25 27 PM" src="https://user-images.githubusercontent.com/9487286/101312977-f74fdf00-3809-11eb-861c-4685b54c1b58.png">

**Comment by tim-hellhake** [comment]
> Not sure this is an add-on issue or a WebThings UI issue

The adapter only reports a list of properties to the gateway.
The UI decides how to render it.

I added a section in the config where you can disable some of the properties.
If you want to disable more properties, just let me know.

**Comment by kgiori** [comment]
Perfect solution. Works great!!
