### ISSUE TITLE
Setting URL

### ISSUE THREAD

**Issue by BRODRICK-WELTS** [tim-hellhake/sonos-adapter#23]
I can't set the URL from Rules or Macros it appears to be an action not a variable?

**Comment by tim-hellhake** [comment]
That's correct.
The adapter exposes a `playUri` action with an input.
Unfortunately, the [issue](WebThingsIO/gateway#996) for the rule system is still open.

**Comment by tim-hellhake** [comment]
That's correct.
The adapter exposes a `playUri` action with an input.
Unfortunately, the [issue](https://github.com/WebThingsIO/gateway/issues/996) for the rule system is still open.

**Comment by tim-hellhake** [comment]
There is also an open [issue](https://github.com/bewee/macrozilla/issues/39) in the Macros repo.

**Comment by bewee** [comment]
> There is also an open [issue](https://github.com/bewee/macrozilla/issues/39) in the Macros repo.

Hope the latest release resolves this problem for macros

**Comment by tim-hellhake** [comment]
@bewee Nice work!
@BRODRICK-WELTS
The new update of the macros adapter is out.
Did you have a chance to test it?

**Comment by tim-hellhake** [comment]
I'm closing this now as the latest macros adapter seems to solve the problem.
