### ISSUE TITLE
tie "playing" property to an on/off property to toggle music from main icon

### ISSUE THREAD

**Issue by kgiori** [tim-hellhake/sonos-adapter#7]
Instead of having to open the icon detail to play music, it would be nice if the Sonos Thing Description (TD) were defined as an on/off switch:
https://iot.mozilla.org/schemas/#OnOffSwitch

Further enhancement idea is to include the ToggleAction, which would stop playing or start playing based on toggling the current "playing" state. 

On the Mozilla schema side, I think we need to add a media player schema and capability definition, that incorporates the properties, actions, and events of this add-on and several others that represent similar capability devices.

**Comment by freaktechnik** [comment]
I had started https://github.com/mozilla-iot/schemas/pull/32 ages ago to allow things like that.

**Comment by kgiori** [comment]
Also, there are different needs based on whether you are playing from a music library or just live streaming from the Internet. In the case of live streaming, the control needs are much simpler. I think the only controls I need/use are:
* playing/not playing
* volume
* track
In my case, "connecting" the internet channel was done via the Sonos app -- I stream an Internet Radio channel from Tune-In for example.

**Comment by tim-hellhake** [comment]
@kgiori The `playing` property should now be an `OnOffProperty`.
